### ISSUE TITLE
Finished solution?

### ISSUE THREAD

**Issue by xXSTrikeXx** [rikmeijer/nextcloud-onedrive#1]
Did you found a solution for connecting to onedrive? I´ve installed it and wondered about the emptiness after passing all (download) error while enabling the app in the app list. I checked the scource files then and I understood why it´s empty. It´s in an AAaaA('32)lpha status. Did you found a solution or why you hadn´t carried on it? I wiill be happy when i find any solutions :D

**Comment by rikmeijer** [comment]
Hi,Sorry, never had time to actually implement anything and by now I have forgotten if I had a proper solution back then...Sent from my Wileyfox phoneOp 14 feb. 2018 21:26 schreef xXSTrikeXx <notifications@github.com>:Did you found a solution for connecting to onedrive? I´ve installed it and wondered about the emptiness after passing all (download) error while enabling the app in the app list. I checked the scource files then and I understood why it´s empty. It´s in an AAaaA('32)lpha status. Did you found a solution or why you hadn´t carried on it? I wiill be happy when i find any solutions :D

**Comment by xXSTrikeXx** [comment]
No problem, was just wondering that i found this on Github, so i tried myself, because dropbox v2 isnt in the appstore already (only on github). So i tried to ask for a status ;)
